---
title: "Descripción de variables cuantitativas y cualitativas"
author: "Mónica Lara Escalante"
output: html_document
---

## Ejercicios: con la base de datos "concentradohogar":

1. ¿Cuántos son hogares con jefatura femenina y son de estrato socioeconómico bajo?
2. ¿Cuántos son hogares con jefatura masculina y son de estrato socioeconómico bajo?
3. ¿Cuántos son hogares con jefatura femenina y viven en hogares "ampliados"?
4. ¿Cuántos son hogares con jefatura masculina y viven en hogares "ampliados"?
5. Genera una nueva variable dummy/dicotómica con el tamaño de localidad: una categoría con localidades de menos de 2500 habitantes y otra categoría con localidades igual o mayor a 2500 habitantes. ¿Cuántos hogares están en cada categoría? 
Haz una tabla cruzada con la variable nueva y la original para comparar los resultados. 
6. Genera una nueva variable que recodifique la variable de estrato socioeconómico en bajo y alto. ¿Cuántos hogares están en cada categoría?
Haz una tabla cruzada con la variable nueva y la original para comparar los resultados. 
7. Descarga la base de datos "viviendas.csv". Une la base de datos de vivienda con la base de datos de hogar y responde, ¿cuántas viviendas son departamentos en edificios y jefaturas de hogar femeninas?
8. Descarga el csv que corresponde a los ingresos del programa de jóvenes construyendo el futuro "ingresos_jcf". Por folio de vivienda, folio del hogar e integrante, convierte de wide a long los ingresos del primer mes, segundo mes, tercer mes, cuarto mes, quinto mes y sexto mes. ¿Cuál es el ingreso total por cada uno de los meses?
9. Con la base de datos de concentradohogar, agrégale etiquetas a la variable de estrato socioeconómico (original) y elabora una tabla de frecuencias con las frecuencias absolutas y relativas.
10. Con la base de datos de concentradohogar, calcula las medidas de tendencia central (media, mediana, moda), de posición (cuartiles, deciles y percentiles), de variabilidad (rango, rango intercuartílico, varianza y desviación estándar) de la variable edad de la jefatura del hogar.
11. Interpreta los resultados de manera general donde contemples las 10 preguntas anteriores. ¿Qué sobresale, qué diferencias hay entre jefaturas femeninas y masculinas, etc?
